version: "3.9"

services:

  catalogue:
    build: ./catalogue
    container_name: catalogue
    networks:
      - shopflow-net
    # No public ports - internal only

  checkout:
    build: ./checkout
    container_name: checkout
    networks:
      - shopflow-net
    ports:
      - "6002:5002"
    depends_on:
      - catalogue

  notifications:
    build: ./notifications
    container_name: notifications
    networks:
      - shopflow-net
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - shopflow-net
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC receiver
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - shopflow-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - shopflow-net
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
    - grafana-data:/var/lib/grafana
  
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    networks:
      - shopflow-net
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
    - shopflow-net
volumes:
  grafana-data:

networks:
  shopflow-net:
