apiVersion: 1

groups:
  - orgId: 1
    name: ShopFlow SLOs
    folder: ShopFlow
    interval: 1m
    rules:
      - uid: checkout-latency
        title: Checkout High Latency
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: histogram_quantile(0.95, sum by (le, endpoint)(rate(http_request_duration_seconds_bucket{job="checkout"}[5m])))
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.3
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
              refId: C
              type: threshold
        noDataState: OK
        execErrState: OK
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Checkout p95 latency above 300ms

      - uid: error-rate
        title: High Error Rate
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.01
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
              refId: C
              type: threshold
        noDataState: OK
        execErrState: OK
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Error rate above 1%