#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose-v2
  - curl
  - git

runcmd:
  # Install Azure CLI properly
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
  # Start Docker
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker azureuser

  # Login to ACR via Managed Identity
  - az login --identity --client-id ${identity_client_id}
  - az acr login --name ${acr_name}

  # Clone repo
  - git clone ${github_repo} /home/azureuser/shopflow
  - chown -R azureuser:azureuser /home/azureuser/shopflow

  # Fetch secrets from Key Vault
  - |
    GRAFANA_PASSWORD=$(az keyvault secret show \
      --vault-name ${kv_name} \
      --name grafana-admin-password \
      --query value -o tsv)
    echo "GRAFANA_PASSWORD=$${GRAFANA_PASSWORD}" >> /home/azureuser/shopflow/.env
    echo "ACR=${acr_name}.azurecr.io" >> /home/azureuser/shopflow/.env
    echo "IMAGE_TAG=latest" >> /home/azureuser/shopflow/.env

  # Start the stack
  - cd /home/azureuser/shopflow && docker compose -f docker-compose-cloud.yml up -d

  - |
    sleep 30
    GRAFANA_PASSWORD=$(az keyvault secret show \
      --vault-name ${kv_name} \
      --name grafana-admin-password \
      --query value -o tsv)
    curl -s -X POST \
      http://admin:$${GRAFANA_PASSWORD}@localhost:3000/api/dashboards/db \
      -H "Content-Type: application/json" \
      -d @/home/azureuser/shopflow/grafana/dashboards/shopflow-metrics.json